# $DOTFILES/bash/bash_logout
#
# Entry point for bash logout processing (interactive shells).
#
# 1. Inherit, read, or assign the DOTFILES variable -- there's no good way
#    to compute it. Regardless, the value is exported since it shouldn't 
#    change for subshells.
#
if [[ ! $DOTFILES ]]
then
	if [[ -f $HOME/.dotfiles && -r $HOME/.dotfiles && -s $HOME/.dotfiles ]]
	then
		DOTFILES="$(head -n 1 "$HOME/.dotfiles")"
	else
		DOTFILES="$HOME/dotfiles"
	fi
fi

export DOTFILES

#
# 2. Set the shell type (bash) and the login status (login) here, since
#    this information is determined by the fact of reading this file.
#    Don't export SESSION variables, since a subshell might have different
#    parameters. (Won't be a login shell, might not be bash, etc.)
#
SHRC_SHELL_FLAVOR="${SHRC_SHELL_FLAVOR:-bash}"
SHRC_SCRIPT_DIR="${SHRC_SCRIPT_DIR:-${DOTFILES}/${SHRC_SHELL_FLAVOR}}"

source "${SHRC_SCRIPT_DIR}/logout.sh"
